openapi: 3.0.0
info:
  title: Evaluation API
  version: 1.0.0
tags:
  - name: Evaluation
paths:
  /api/v1/evaluation/run:
    post:
      summary: Sart the evaluation of a conversation
      tags: [Evaluation]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunEvaluationRequest"
      responses:
        200:
          description: Evaluation successfully executed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RunEvaluationResponse"
        404:
          description: Conversation or Simulation not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Conversation 6569177d47be6ae122cc8aa5 not found!"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: INTERNAL_SERVER_ERROR
                  message:
                    type: string
                    example: Internal server error occurred
                  details:
                    type: string
                    example: Error
components: 
  schemas:
    RunEvaluationRequest:
      type: object
      properties:
        conversation:
          type: string
          example: 656499ee83e3e06db0309f25
        simulation:
          type: string
          example: 656499ee83e3e06db0309f25
        isLast:
          type: boolean
        optimization:
          type: string
          example: 656499ee83e3e06db0309f25
    RunEvaluationResponse:
      type: object
      properties:
        optimization:
          type: string
          example: 656499ee83e3e06db0309f25
        simulation:
          type: string
          example: 656499ee83e3e06db0309f25
        evaluation:
          type: string
          example: 656499ee83e3e06db0309f25
