openapi: 3.0.0
info:
  title: Evaluation API
  version: 1.0.0
tags:
  - name: Evaluation
paths:
  /api/v1/evaluation/run:
    post:
      summary: Start the evaluation of a conversation
      tags: [Evaluation]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RunEvaluationRequest"
      responses:
        201:
          description: Evaluation successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EvaluationDocument"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: INTERNAL_SERVER_ERROR
                  message:
                    type: string
                    example: Internal server error occurred
                  details:
                    type: string
                    example: Error
  /api/v1/evaluation/results-for-conversation/{conversationId}:
    get:
      summary: Retrieve evaluation results for conversation
      tags: [Evaluation]
      parameters:
        - in: path
          name: conversationId
          required: true
          schema:
            type: string
            example: 6553a127fcad73273655d634
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EvaluationResultForConversation"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Conversation 6553a127fcad73273655d634 not found!"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: INTERNAL_SERVER_ERROR
                  message:
                    type: string
                    example: Internal server error occurred
                  details:
                    type: string
                    example: Error
  /api/v1/evaluation/results-for-simulation/{simulationId}:
    get:
      summary: Retrieve evaluation results for simulation
      tags: [Evaluation]
      parameters:
        - in: path
          name: simulationId
          required: true
          schema:
            type: string
            example: 6553a127fcad73273655d634
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EvaluationResultForSimulation"
        404:
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Simulation 6553a127fcad73273655d634 not found!"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: INTERNAL_SERVER_ERROR
                  message:
                    type: string
                    example: Internal server error occurred
                  details:
                    type: string
                    example: Error
components: 
  schemas:
    RunEvaluationRequest:
      type: object
      properties:
        conversationID:
          type: string
          example: 656499ee83e3e06db0309f25
        simulationID:
          type: string
          example: 656499ee83e3e06db0309f25
        isLastConversation:
          type: boolean
        shouldOptimize:
          type: boolean
    EvaluationDocument:
      type: object
      properties:
        _id:
          type: string
          example: 656499ee83e3e06db0309f25
        simulation:
          $ref: "#/components/schemas/SimulationDocument"
        conversation:
          $ref: "#/components/schemas/ConversationDocument"
        metrics:
          type: object
          additionalProperties:
            type: number
        createdAt:
          type: string
          example: "2023-11-14T16:32:39.419Z"
        updatedAt:
          type: string
          example: "2023-11-14T16:32:39.419Z"
        __v:
          type: integer
          example: 0
    SimulationDocument:
      type: object
      properties:
        _id:
          type: string
          example: 6553a127fcad73273655d634
        scenario:
          type: string
          example: SLOT_FILLING
        type:
          type: string
          example: AUTOMATED
        domain:
          type: string
          example: INSURANCE
        agents:
          type: array
          items:
            oneOf:
              - $ref: '#/components/schemas/ServiceAgent'
              - $ref: '#/components/schemas/UserAgent'
        conversations:
          type: array
          items:
            $ref: '#/components/schemas/ConversationDocument'
        status:
          type: string
          enum: [SCHEDULED, STARTED, FINISHED]
        createdAt:
          type: string
          example: "2023-11-14T16:32:39.419Z"
        updatedAt:
          type: string
          example: "2023-11-14T16:32:39.419Z"
        __v:
          type: integer
          example: 0
    ConversationDocument:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
          example: []
        start:
          type: string
          format: date
          example: 2023-12-12
        status:
          type: string
          enum: [STARTED, FINISHED]
        usedEndpoints:
          type: array
          items:
            type: string
          example: []
    EvaluationResultForConversation:
      type: object
      properties:
        status:
          type: string
          enum:
            - evaluated
            - in_progress
            - not_evaluated
        score:
          type: number
        metrics:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                enum:
                  - success
                  - response_time
                  - message_count
              value:
                type: number
              weight:
                type: number
    EvaluationResultForSimulation:
      type: object
      properties:
        averageScore:
          type: number
        conversations:
          type: array
          items:
            type: object
            properties:
              conversation:
                type: string
                example: 656499ee83e3e06db0309f25
              score:
                type: number
              metrics:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      enum:
                        - success
                        - response_time
                        - message_count
                    value:
                      type: number
                    weight:
                      type: number
