version: "3.9"

services:
  mongodb:
    image: mongo:latest
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - db:/data/db
  mongo-express:
    depends_on:
      - mongodb  
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    env_file: .env
    ports:
      - $MONGOEXPRESS_LOCAL_PORT:$MONGOEXPRESS_DOCKER_PORT
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_PORT=$MONGODB_DOCKER_PORT
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGOEXPRESS_BASICAUTH_USERNAME
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGOEXPRESS_BASICAUTH_PASSWORD
  app:
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file: .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
    stdin_open: true
    tty: true

volumes:
  db: