enum MsgType {
  HUMANINPUT = 'HUMANINPUT',
  SYSTEMPROMPT = 'SYSTEMPROMPT',
  TOOLCALL = 'TOOLCALL',
  TOOLOUTPUT = 'TOOLOUTPUT',
  MSGTOUSER = 'MSGTOUSER',
  ROUTE = 'ROUTE',
  HANGUP = 'HANGUP',
}

export { MsgType };
